// <auto-generated />
using AlocacaoVeiculosAssistencia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlocacaoVeiculosAssistencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811190347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.GruposVeiculos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("GruposVeiculos");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.PlanosAssistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ValorCobertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("PlanosAssistencia");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.Veiculos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.VeiculosAssistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("VeiculoId", "PlanoId")
                        .IsUnique();

                    b.ToTable("VeiculosAssistencia");
                });

            modelBuilder.Entity("EmpresasAssistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EmpresasAssistencia");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.PlanosAssistencia", b =>
                {
                    b.HasOne("EmpresasAssistencia", "Empresa")
                        .WithMany("PlanosAssistencia")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.Veiculos", b =>
                {
                    b.HasOne("AlocacaoVeiculosAssistencia.Domain.Entities.GruposVeiculos", "Grupo")
                        .WithMany("Veiculos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.VeiculosAssistencia", b =>
                {
                    b.HasOne("AlocacaoVeiculosAssistencia.Domain.Entities.PlanosAssistencia", "Plano")
                        .WithMany("Veiculos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlocacaoVeiculosAssistencia.Domain.Entities.Veiculos", "Veiculo")
                        .WithMany("Assistencias")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.GruposVeiculos", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.PlanosAssistencia", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("AlocacaoVeiculosAssistencia.Domain.Entities.Veiculos", b =>
                {
                    b.Navigation("Assistencias");
                });

            modelBuilder.Entity("EmpresasAssistencia", b =>
                {
                    b.Navigation("PlanosAssistencia");
                });
#pragma warning restore 612, 618
        }
    }
}
