name: CI - Alocacao Veiculos

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:

  backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore AlocacaoVeiculosAssistencia/AlocacaoVeiculosAssistencia/AlocacaoVeiculosAssistencia.csproj

      - name: Compilar backend
        run: dotnet build AlocacaoVeiculosAssistencia/AlocacaoVeiculosAssistencia/AlocacaoVeiculosAssistencia.csproj --configuration Release --no-restore
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configurar Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: Front-AlocacaoVeiculo/AlocacaoVeiculos/package-lock.json
      - name: Instalar dependencias
        working-directory: Front-AlocacaoVeiculo/AlocacaoVeiculos
        run: npm ci

      - name: Compilar Angular
        working-directory: Front-AlocacaoVeiculo/AlocacaoVeiculos
        run: npm run build